services:
  postgres:
    image: postgres:16-alpine
    container_name: techstore-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: techstore
      POSTGRES_PASSWORD: techstore
      POSTGRES_DB: techstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
